# -*- coding: utf-8 -*-
"""final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ie6HBiJ4uWnFNLcYMPvq7de2QxaxRceW

# **Working with Data - Goodreads Dataset**

### **Part 1 - Web scraping**

1. Setup and Configuration
"""

import pandas as pd
import requests
from bs4 import BeautifulSoup
import os
import time
import random
import re
from google.colab import files
from IPython.display import display

BASE_URL = "https://www.goodreads.com/list/show/1.Best_Books_Ever"
REF_PARAM = "&ref=ls_pl_car_0"

FINAL_TARGET_PAGE = 100

PAGES_PER_BATCH = 5 #scraps 5 pages at once

RESUME_START_PAGE = 1 # where the scraping resumes

FINAL_FILENAME = "goodreads_dataset_10000_FINAL.csv"

HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/555.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/555.36',
    'Accept-Language': 'en-US,en;q=0.9,ru;q=0.8',
    'Referer': 'https://www.goodreads.com/'
}

"""2. Data Cleaning and Utilities"""

import re

def clean_number(text):
    """
    Cleans a string containing numbers, handles commas, and converts to int.
    Used for Ratings_Count, Num_Reviews.
    """
    if text:
        # Remove non-digit and non-comma characters
        cleaned = re.sub(r'[^\d,]', '', text)
        return int(cleaned.replace(',', ''))
    return None

def clean_rating(text):
    """
    Extracts the floating-point rating from a string.
    Used for Avg_Rating.
    """
    if text:
        # Finds the pattern of one or more digits, a decimal point, and one or more digits
        match = re.search(r'(\d+\.\d+)', text)
        return float(match.group(1)) if match else None
    return None

"""3. Core Scraping Functions"""

def scrape_book_details(session, book_url):
    """Scrapes year, page count, and reviews from the individual book page."""
    # ULTRA-SAFE speed for individual book pages
    time.sleep(random.uniform(5, 10))
    details = {'Year': None, 'Num_Reviews': None, 'Num_Pages': None}

    try:
        book_response = session.get(book_url, headers=HEADERS, timeout=15)
        book_response.raise_for_status()
        book_soup = BeautifulSoup(book_response.text, 'html.parser')

        body_text = book_soup.get_text()

        # Extract Year from publicationInfo element
        date_element = book_soup.find('p', {'data-testid': 'publicationInfo'})
        if date_element:
            text = date_element.get_text(strip=True)
            year_match = re.search(r'(\d{4})', text)
            if year_match:
                details['Year'] = int(year_match.group(1))

        # Extract Pages using regex across the whole body text
        pages_match = re.search(r'(\d+)\s+(?:pages|page)', body_text, re.IGNORECASE)
        if pages_match:
            details['Num_Pages'] = int(pages_match.group(1))

        # Extract Reviews using regex across the whole body text
        reviews_match = re.search(r'([\d,]+)\s+reviews', body_text, re.IGNORECASE)
        if reviews_match:
            details['Num_Reviews'] = clean_number(reviews_match.group(1))

    except Exception as e:
        # Pass silently on error, details will remain None
        pass

    return details

def scrape_goodreads_data():
    """Main function to scrape a batch of list pages."""
    global RESUME_START_PAGE

    start_page = RESUME_START_PAGE
    end_page_for_batch = min(start_page + PAGES_PER_BATCH, FINAL_TARGET_PAGE + 1)

    print(f"Starting Goodreads BATCH scraping. Range: Pages {start_page} to {end_page_for_batch - 1}...")

    all_data = []
    session = requests.Session()
    session.headers.update(HEADERS)

    initial_id_count = (RESUME_START_PAGE - 1) * 100

    for page in range(start_page, end_page_for_batch):
        url = f"{BASE_URL}?page={page}{REF_PARAM}"
        print(f"Scraping List Page {page}/{FINAL_TARGET_PAGE}")

        try:
            response = session.get(url, timeout=20)
            response.raise_for_status()
            soup = BeautifulSoup(response.text, 'html.parser')
            item_rows = soup.find_all('tr', itemscope=True, itemtype='http://schema.org/Book')

            if not item_rows:
                print("No items found on this page. Stopping early.")
                break

            for row in item_rows:
                book_data = {}
                book_url = None

                try:
                    # 1. Scrape data from the List Page
                    title_tag = row.find('a', class_='bookTitle')
                    book_data['Title'] = title_tag.find('span', itemprop='name').get_text(strip=True) if title_tag else 'N/A'
                    book_url = f"https://www.goodreads.com{title_tag['href']}"

                    author_tag = row.find('a', class_='authorName')
                    book_data['Author'] = author_tag.get_text(strip=True) if author_tag else 'N/A'

                    rating_container = row.find('span', class_='minirating')
                    rating_text = rating_container.get_text(strip=True) if rating_container else ''
                    book_data['Avg_Rating'] = clean_rating(rating_text)

                    ratings_count_match = re.search(r'—\s([\d,]+)\sratings', rating_text)
                    book_data['Ratings_Count'] = clean_number(ratings_count_match.group(1)) if ratings_count_match else None

                    book_data['URL'] = book_url

                    # 2. Scrape data from the Detail Page (nested call)
                    details = scrape_book_details(session, book_url)
                    book_data['Number of Reviews'] = details['Num_Reviews']
                    book_data['Year'] = details['Year']
                    book_data['Number of Pages'] = details['Num_Pages']

                    book_data['ID'] = initial_id_count + len(all_data) + 1
                    all_data.append(book_data)

                except Exception as e:
                    continue

            print(f"Items scraped from page: {len(item_rows)}. Total scraped in this run: {len(all_data):,}")

        except requests.exceptions.RequestException as e:
            print(f"CRITICAL ERROR fetching page {page}: {e}")
            break

        # Safety delay between list pages
        sleep_time = random.uniform(10, 15)
        print(f"Pausing for {sleep_time:.2f} seconds...")
        time.sleep(sleep_time)

    return pd.DataFrame(all_data), page + 1

"""4. Main Execution and Data Overview"""

def create_csv_file(df_new):
    """
    Creates or appends to the final CSV file, handling file existence and data types.
    Uses sep=';' and decimal=',' for Excel compatibility.
    """
    filename = FINAL_FILENAME
    df_final = pd.DataFrame()

    try:
        # 1. Load existing data
        df_existing = pd.read_csv(FINAL_FILENAME, sep=';', decimal=',')

        # Type casting for safer concatenation
        for col in ['Year', 'Number of Reviews', 'Number of Pages']:
            df_existing[col] = df_existing[col].astype('Int64', errors='ignore')

        # 2. Combine old and new data
        df_final = pd.concat([df_existing, df_new], ignore_index=True)
        # 3. Recalculate ID for the combined file
        df_final['ID'] = range(1, len(df_final) + 1)

        print(f"Appended {len(df_new):,} new records to the existing file.")

    except FileNotFoundError:
        df_final = df_new
        print("Created new file (no existing data found for append).")

    # Final formatting and column order
    df_final['Year'] = df_final['Year'].astype('Int64', errors='ignore')

    FINAL_COLUMNS = [
        'ID', 'Title', 'Author', 'Avg_Rating', 'Ratings_Count',
        'Number of Reviews', 'Year', 'Number of Pages', 'URL'
    ]

    df_final = df_final[FINAL_COLUMNS]

    # Save the file (using ; and , for Excel compatibility)
    df_final.to_csv(FINAL_FILENAME, index=False, encoding='utf-8-sig', sep=';', decimal=',')

    print(f"\nCSV File Updated/Created: {FINAL_FILENAME}")
    print(f"Total Records in FINAL file: {len(df_final):,}")

    return df_final


def main():
    """Main execution function for project status check, scraping, and final output."""
    print("=" * 80)
    print(f"WEB SCRAPING PROJECT - GOODREADS")
    print("=" * 80)

    start_time = time.time()
    df = pd.DataFrame()
    global RESUME_START_PAGE
    next_start_page_for_summary = RESUME_START_PAGE
    current_rows = 0

    # --- 1. PROJECT STATUS CHECK AND RESUME SETUP ---
    try:
        if os.path.exists(FINAL_FILENAME):
            df = pd.read_csv(FINAL_FILENAME, sep=';', decimal=',')
            current_rows = len(df)

            if current_rows >= FINAL_TARGET_PAGE * 100:
                print("\n*Scraping complete!*")
                next_start_page_for_summary = FINAL_TARGET_PAGE + 1
            else:
                RESUME_START_PAGE = (current_rows // 100) + 1
                print(f"*RESUME_START_PAGE automatically updated to:* {RESUME_START_PAGE}")
        else:
            print(f"File '{FINAL_FILENAME}' not found. Starting with configured {RESUME_START_PAGE}.")

    except Exception as e:
        print(f"CRITICAL ERROR reading file {FINAL_FILENAME}: {e}")

    # --- 2. RUN SCRAPING BATCH (if not complete) ---
    if next_start_page_for_summary <= FINAL_TARGET_PAGE:
        print("\n--- STARTING SCRAPING BATCH ---")
        df_new, next_page_scraped = scrape_goodreads_data()

        next_start_page_for_summary = next_page_scraped

        if not df_new.empty:
            df = create_csv_file(df_new)

    # --- 3. DATA OVERVIEW AND SUMMARY ---
    end_time = time.time()

    # Data Preview
    if not df.empty:
        print("\n" + "=" * 80)
        print("DATA PREVIEW:")
        print("=" * 80)

        print("\n--- TOP 5 RECORDS ---")
        display(df.head(5))

        print("\n--- BOTTOM 5 RECORDS ---")
        display(df.tail(5))

    # Final Summary
    print("\n" + "=" * 80)
    print("PROJECT SUMMARY:")
    print("=" * 80)

    if not df.empty:
        print(f"Dataset size: {len(df):,} records")

    if next_start_page_for_summary <= FINAL_TARGET_PAGE:
        print(f"\n➡ *NEXT RUN:* Set RESUME_START_PAGE = {next_start_page_for_summary} for the next batch.")
    else:
        print("\nScraping is fully complete!")
        # files.download(FINAL_FILENAME) # Uncomment to auto-download in Colab

    print(f"Total Runtime: {end_time - start_time:.2f} seconds")
    print("=" * 80)

if __name__ == "__main__":
    main()

# Part 2 — Data Cleaning & Preparation
# Version: Remove rows with empty cells and add 2 derived features

# ========================
# Stage 1: Data Loading and Initial Inspection
# ========================

import pandas as pd
import numpy as np
import warnings
import os
warnings.filterwarnings('ignore')

# Load data with correct delimiters
df = pd.read_csv("goodreads_dataset_10000_FINAL.csv", sep=';', decimal=',')

print("=" * 80)
print(" DATA INSPECTION - INITIAL DATA EXPLORATION")
print("=" * 80)

# 1.1. View first records
print("\n 1. FIRST 5 RECORDS TO UNDERSTAND STRUCTURE:")
print(df.head())

# 1.2. General information about data structure
print("\n 2. GENERAL DATAFRAME INFORMATION:")
print(f"Dataset size: {df.shape[0]} rows, {df.shape[1]} columns\n")
print("Data types and missing values information:")
print(df.info())

# 1.3. Statistical description of numerical columns
print("\n 3. STATISTICAL DESCRIPTION OF NUMERICAL COLUMNS:")
print(df.describe(include=[np.number]))

# 1.4. Statistical description of text columns
print("\n 4. STATISTICAL DESCRIPTION OF TEXT COLUMNS:")
print(df.describe(include=[object]))

# ========================
# Stage 2: Missing Values Analysis
# ========================

print("=" * 80)
print(" MISSING VALUES ANALYSIS")
print("=" * 80)

# 2.1. Count missing values by column
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100

missing_df = pd.DataFrame({
    'Missing Values': missing_values,
    'Percentage Missing': missing_percentage.round(2)
})

print("\n MISSING VALUES BY COLUMN:")
print(missing_df[missing_df['Missing Values'] > 0])

print("\n INSIGHTS:")
print("We will remove ALL rows that contain ANY missing values")
print("This ensures complete data for analysis")

# ========================
# Stage 3: Duplicates Analysis
# ========================

print("=" * 80)
print(" DUPLICATES ANALYSIS")
print("=" * 80)

# 3.1. Check for complete duplicates
full_duplicates = df.duplicated().sum()
print(f"\n Complete duplicates (all columns match): {full_duplicates}")

# 3.2. Check duplicates by key fields
print("\n Checking duplicates by title and author:")
title_author_duplicates = df.duplicated(subset=['Title', 'Author']).sum()
print(f"Duplicates by Title + Author: {title_author_duplicates}")

if title_author_duplicates > 0:
    print("\nExamples of duplicates:")
    duplicates = df[df.duplicated(subset=['Title', 'Author'], keep=False)]
    print(duplicates[['Title', 'Author']].head(10))

print("\n INSIGHTS:")
print("We will remove duplicates to ensure data quality")

# ========================
# Stage 4: Data Types Analysis
# ========================

print("=" * 80)
print(" DATA TYPES ANALYSIS AND CONVERSION")
print("=" * 80)

print("\n CURRENT DATA TYPES:")
print(df.dtypes)

# 4.1. Check numerical columns for non-numeric values
print("\n Checking numerical columns for anomalies:")

numeric_cols = ['Avg_Rating', 'Ratings_Count', 'Number of Reviews', 'Year', 'Number of Pages']
for col in numeric_cols:
    if col in df.columns:
        non_numeric = pd.to_numeric(df[col], errors='coerce').isna().sum() - df[col].isna().sum()
        if non_numeric > 0:
            print(f"Column '{col}': {non_numeric} non-numeric values")

# ========================
# Stage 5: Data Cleaning
# ========================

print("=" * 80)
print(" STARTING DATA CLEANING PROCESS")
print("=" * 80)

# Store original data shape
original_shape = df.shape
print(f"Original dataset shape: {original_shape[0]} rows, {original_shape[1]} columns")

# 5.1. Text Fields Cleaning
print("\n TEXT FIELDS CLEANING:")

# 5.1.1. Book titles cleaning
if 'Title' in df.columns:
    # Remove extra spaces
    df['Title'] = df['Title'].astype(str).str.strip()
    # Convert to proper case
    df['Title'] = df['Title'].str.title()
    print("✓ Cleaned 'Title' field")

# 5.1.2. Author names cleaning
if 'Author' in df.columns:
    # Remove extra spaces
    df['Author'] = df['Author'].astype(str).str.strip()
    # Standardize author name format
    df['Author'] = df['Author'].str.title()
    print("✓ Cleaned 'Author' field")

# 5.2. REMOVE ALL ROWS WITH ANY MISSING VALUES
print("\n" + "=" * 80)
print(" REMOVING ALL ROWS WITH ANY MISSING VALUES")
print("=" * 80)

print("\n STRATEGY: Remove any row that contains at least one empty cell")
print("This creates a complete dataset without any missing values")

# Count missing values before removal
missing_before = df.isnull().sum().sum()
rows_before = len(df)
print(f"\nBefore removal:")
print(f"  Total rows: {rows_before:,}")
print(f"  Total missing values: {missing_before}")
print(f"  Rows with any missing values: {df.isnull().any(axis=1).sum():,}")

# Remove ALL rows with ANY missing values
df = df.dropna()

rows_after = len(df)
rows_removed = rows_before - rows_after
missing_after = df.isnull().sum().sum()

print(f"\nAfter removal:")
print(f"  Total rows: {rows_after:,}")
print(f"  Total missing values: {missing_after}")
print(f"  Rows removed: {rows_removed:,}")
print(f"  Percentage of rows kept: {(rows_after/rows_before*100):.1f}%")

if rows_removed > 0:
    print(f"\n✅ Successfully removed {rows_removed:,} rows with missing values")
    print("✅ Dataset now has NO missing values in any cell")
else:
    print("\n✅ Dataset already had no missing values")

# 5.3. Remove duplicates
print("\n" + "=" * 80)
print(" REMOVING DUPLICATES")
print("=" * 80)

# Remove complete duplicates
duplicates_before = df.duplicated().sum()
if duplicates_before > 0:
    df = df.drop_duplicates()
    print(f"✓ Removed {duplicates_before} complete duplicates")

# Remove duplicates by title and author
if 'Title' in df.columns and 'Author' in df.columns:
    title_author_dups = df.duplicated(subset=['Title', 'Author']).sum()
    if title_author_dups > 0:
        df = df.drop_duplicates(subset=['Title', 'Author'], keep='first')
        print(f"✓ Removed {title_author_dups} duplicates by Title+Author")

print(" Duplicate removal complete")

# 5.4. Convert data types properly
print("\n" + "=" * 80)
print(" CONVERTING DATA TYPES")
print("=" * 80)

# Convert Avg_Rating to float
if 'Avg_Rating' in df.columns:
    df['Avg_Rating'] = pd.to_numeric(df['Avg_Rating'], errors='coerce').astype('float64')
    print(f"✓ Converted 'Avg_Rating' to float64")

# Convert integer columns
int_columns = ['Ratings_Count', 'Number of Reviews', 'Year', 'Number of Pages', 'ID']
for col in int_columns:
    if col in df.columns:
        # Convert to integer
        df[col] = pd.to_numeric(df[col], errors='coerce').round().astype('int64')
        print(f"✓ Converted '{col}' to int64")

print("✅ Data type conversion complete")

# 5.5. Data validation
print("\n" + "=" * 80)
print(" DATA VALIDATION")
print("=" * 80)

# Validate rating range (0-5)
if 'Avg_Rating' in df.columns:
    invalid_ratings = df[(df['Avg_Rating'] < 0) | (df['Avg_Rating'] > 5)]
    if len(invalid_ratings) > 0:
        df['Avg_Rating'] = np.where(
            df['Avg_Rating'] < 0, 0,
            np.where(df['Avg_Rating'] > 5, 5, df['Avg_Rating'])
        )
        print(f"✓ Fixed {len(invalid_ratings)} invalid ratings")

    print(f"  Rating range: {df['Avg_Rating'].min():.2f} to {df['Avg_Rating'].max():.2f}")

# Validate year range (reasonable publication years)
if 'Year' in df.columns:
    current_year = pd.Timestamp.now().year
    invalid_years = df[(df['Year'] < 1000) | (df['Year'] > current_year)]

    if len(invalid_years) > 0:
        # Calculate median year from valid years only
        valid_years = df[(df['Year'] >= 1000) & (df['Year'] <= current_year)]['Year']
        if len(valid_years) > 0:
            median_year = int(round(valid_years.median()))
            df.loc[invalid_years.index, 'Year'] = median_year
            print(f"✓ Fixed {len(invalid_years)} invalid publication years")
            print(f"  Replaced with median year: {median_year}")

    print(f"  Year range: {df['Year'].min()} to {df['Year'].max()}")

# Validate Number of Pages (positive values)
if 'Number of Pages' in df.columns:
    negative_pages = df[df['Number of Pages'] < 0]
    if len(negative_pages) > 0:
        # Replace negative pages with median positive value
        positive_median = df[df['Number of Pages'] > 0]['Number of Pages'].median()
        if not pd.isna(positive_median):
            positive_median = int(round(positive_median))
            df.loc[negative_pages.index, 'Number of Pages'] = positive_median
            print(f"✓ Fixed {len(negative_pages)} negative page counts")
            print(f"  Replaced with median: {positive_median} pages")

    print(f"  Pages range: {df['Number of Pages'].min()} to {df['Number of Pages'].max()} pages")

print("✅ Data validation complete")

# ========================
# Stage 6: Creating 2 Derived Features
# ========================

print("=" * 80)
print(" CREATING 2 DERIVED FEATURES")
print("=" * 80)

print("\n EXPLANATION: We will add only 2 new columns derived from existing data")
print("These features will provide additional insights for analysis.")

# 6.1. Feature 1: Book Age (years since publication)
print("\n1.  CREATING 'Book_Age' FEATURE:")

if 'Year' in df.columns:
    current_year = pd.Timestamp.now().year
    df['Book_Age'] = current_year - df['Year']

    print(f"   Formula: 'Book_Age' = Current Year ({current_year}) - Publication Year")
    print(f"   Purpose: Analyze how book age affects ratings and popularity")
    print(f"   Range: {df['Book_Age'].min()} to {df['Book_Age'].max()} years")
    print(f"   Average book age: {df['Book_Age'].mean():.1f} years")
    print(f"   Oldest book: {df['Book_Age'].max()} years old")
    print(f"   Newest book: {df['Book_Age'].min()} years old")
else:
    print("   Skipped: 'Year' column not found")

# 6.2. Feature 2: Reviews to Ratings Ratio
print("\n2.  CREATING 'Reviews_to_Ratings_Ratio' FEATURE:")

if 'Number of Reviews' in df.columns and 'Ratings_Count' in df.columns:
    # Avoid division by zero
    df['Reviews_to_Ratings_Ratio'] = np.where(
        df['Ratings_Count'] > 0,
        df['Number of Reviews'] / df['Ratings_Count'],
        0
    )

    print(f"   Formula: 'Reviews_to_Ratings_Ratio' = Reviews / Ratings")
    print(f"   Purpose: Measure engagement level (what % of raters write reviews)")
    print(f"   Range: {df['Reviews_to_Ratings_Ratio'].min():.4f} to {df['Reviews_to_Ratings_Ratio'].max():.4f}")
    print(f"   Average ratio: {df['Reviews_to_Ratings_Ratio'].mean():.4f}")
    print(f"   Interpretation: On average, {df['Reviews_to_Ratings_Ratio'].mean()*100:.2f}% of raters write reviews")
else:
    print("   Skipped: Required columns not found")

print("\n✅ SUMMARY OF NEW FEATURES CREATED:")
print("1. Book_Age - Age of book in years (current year - publication year)")
print("2. Reviews_to_Ratings_Ratio - Percentage of raters who write reviews")

# ========================
# Stage 7: Final Verification and Saving
# ========================

print("=" * 80)
print(" FINAL VERIFICATION AND SAVING")
print("=" * 80)

# 7.1. Final data information
print("\n FINAL DATAFRAME INFORMATION:")
print(f"Cleaned dataset shape: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Original columns: {original_shape[1]}, New columns added: {df.shape[1] - original_shape[1]}")

print("\n DATA TYPES AFTER CLEANING:")
print(df.dtypes)

# 7.2. Check for missing values after cleaning
print("\n🔍 CHECKING FOR MISSING VALUES AFTER CLEANING:")
missing_final = df.isnull().sum().sum()
if missing_final == 0:
    print("✅ SUCCESS: No missing values in the dataset!")
    print("✅ Every cell in the dataset has a value")
else:
    print(f"⚠ WARNING: {missing_final} missing values remaining")
    missing_by_col = df.isnull().sum()
    for col, count in missing_by_col[missing_by_col > 0].items():
        print(f"  {col}: {count} missing values")

# 7.3. Summary of cleaning process
print("\n CLEANING PROCESS SUMMARY:")
print(f"Original dataset: {original_shape[0]} rows, {original_shape[1]} columns")
print(f"Cleaned dataset: {df.shape[0]} rows, {df.shape[1]} columns")
print(f"Rows removed due to missing values: {original_shape[0] - rows_after:,}")
print(f"Percentage of original data kept: {(df.shape[0] / original_shape[0] * 100):.1f}%")
print(f"New features created: 2 (Book_Age, Reviews_to_Ratings_Ratio)")

# 7.4. Basic statistics after cleaning
print("\n BASIC STATISTICS AFTER CLEANING:")
print(f"Total books: {df.shape[0]:,}")

if 'Author' in df.columns:
    print(f"Unique authors: {df['Author'].nunique():,}")

if 'Avg_Rating' in df.columns:
    print(f"Average rating: {df['Avg_Rating'].mean():.2f} ± {df['Avg_Rating'].std():.2f}")

if 'Ratings_Count' in df.columns:
    print(f"Total ratings: {df['Ratings_Count'].sum():,}")
    print(f"Average ratings per book: {df['Ratings_Count'].mean():,.0f}")

if 'Number of Reviews' in df.columns:
    print(f"Total reviews: {df['Number of Reviews'].sum():,}")
    print(f"Average reviews per book: {df['Number of Reviews'].mean():,.0f}")

if 'Year' in df.columns:
    print(f"Publication year range: {df['Year'].min()} - {df['Year'].max()}")
    print(f"Average publication year: {df['Year'].mean():.0f}")

if 'Number of Pages' in df.columns:
    print(f"Pages range: {df['Number of Pages'].min()} - {df['Number of Pages'].max()}")
    print(f"Average pages per book: {df['Number of Pages'].mean():.0f}")

# 7.5. Statistics for new features
print("\n STATISTICS FOR NEW DERIVED FEATURES:")

if 'Book_Age' in df.columns:
    print(f"Book_Age (years since publication):")
    print(f"  Range: {df['Book_Age'].min()} to {df['Book_Age'].max()} years")
    print(f"  Mean: {df['Book_Age'].mean():.1f} years")
    print(f"  Std: {df['Book_Age'].std():.1f} years")

if 'Reviews_to_Ratings_Ratio' in df.columns:
    print(f"Reviews_to_Ratings_Ratio:")
    print(f"  Range: {df['Reviews_to_Ratings_Ratio'].min():.4f} to {df['Reviews_to_Ratings_Ratio'].max():.4f}")
    print(f"  Mean: {df['Reviews_to_Ratings_Ratio'].mean():.4f}")
    print(f"  Std: {df['Reviews_to_Ratings_Ratio'].std():.4f}")
    print(f"  Interpretation: Average of {df['Reviews_to_Ratings_Ratio'].mean()*100:.2f}% of raters write reviews")

# 7.6. Save cleaned data with new features
cleaned_filename = "goodreads_dataset_COMPLETE_CLEANED.csv"

print(f"\n SAVING CLEANED DATASET TO FILE: {cleaned_filename}")

# List all columns to be saved
all_columns = df.columns.tolist()
print(f"  Total columns: {len(all_columns)}")
print(f"  Original columns: {original_shape[1]}")
print(f"  New derived features: 2")

df.to_csv(cleaned_filename, index=False, encoding='utf-8-sig', sep=';', decimal=',')

print(f" FILE SAVED SUCCESSFULLY!")
print(f" File size: {os.path.getsize(cleaned_filename) / (1024*1024):.2f} MB")

# 7.7. Show sample of cleaned data
print("\n SAMPLE OF CLEANED DATA WITH NEW FEATURES (first 5 rows):")

# Select key columns to show
sample_columns = []
if 'ID' in df.columns:
    sample_columns.append('ID')
if 'Title' in df.columns:
    sample_columns.append('Title')
if 'Author' in df.columns:
    sample_columns.append('Author')
if 'Year' in df.columns:
    sample_columns.append('Year')
if 'Book_Age' in df.columns:
    sample_columns.append('Book_Age')
if 'Avg_Rating' in df.columns:
    sample_columns.append('Avg_Rating')
if 'Reviews_to_Ratings_Ratio' in df.columns:
    sample_columns.append('Reviews_to_Ratings_Ratio')

if sample_columns:
    print(df[sample_columns].head())
else:
    print(df.head())

print("\n" + "=" * 80)
print("🎉 DATA CLEANING AND PREPARATION COMPLETED SUCCESSFULLY!")
print("=" * 80)
print("\n✅ COMPREHENSIVE SUMMARY:")
print("=" * 50)

print("📋 WHAT WAS DONE:")
print("1. ✅ Initial data inspection (head, info, describe)")
print("2. ✅ Missing values analysis and removal")
print("   - Removed ALL rows with ANY empty cells")
print("   - Result: Complete dataset with NO missing values")
print("3. ✅ Duplicate removal (complete and Title+Author duplicates)")
print("4. ✅ Data type conversion and validation")
print("5. ✅ Created 2 new derived features:")
print("   a) Book_Age: Current year - Publication year")
print("   b) Reviews_to_Ratings_Ratio: Reviews / Ratings")
print("6. ✅ Final validation and saving")

print("\n FINAL DATASET METRICS:")
print(f"   • Original size: {original_shape[0]:,} rows, {original_shape[1]} columns")
print(f"   • Cleaned size: {df.shape[0]:,} rows, {df.shape[1]} columns")
print(f"   • Data kept: {(df.shape[0] / original_shape[0] * 100):.1f}% of rows")
print(f"   • Missing values: {df.isnull().sum().sum()} (0 = perfect)")
print(f"   • New features: 2")

print("\n OUTPUT:")
print(f"   • Saved to: {cleaned_filename}")
print(f"   • File size: {os.path.getsize(cleaned_filename) / (1024*1024):.2f} MB")
print(f"   • Columns: {df.shape[1]} total")

print("\n🔍 KEY INSIGHTS FROM CLEANED DATA:")
if 'Book_Age' in df.columns:
    print(f"   • Average book age: {df['Book_Age'].mean():.1f} years")
if 'Reviews_to_Ratings_Ratio' in df.columns:
    print(f"   • Average reviewer engagement: {df['Reviews_to_Ratings_Ratio'].mean()*100:.2f}%")
if 'Avg_Rating' in df.columns:
    print(f"   • Average rating: {df['Avg_Rating'].mean():.2f}/5")

print("\n✅ The dataset is now:")
print("   • COMPLETE: No missing values in any cell")
print("   • CLEAN: Proper data types and validated ranges")
print("   • ENHANCED: 2 new derived features for analysis")
print("   • READY: For EDA, visualization, and modeling")

"""### Part 3 — Exploratory Data Analysis (EDA)

Setup and Data Loading
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Set style for better visual appeal
sns.set_theme(style="whitegrid", palette="viridis")

# 1. Load the data
file_path = 'goodreads_dataset_COMPLETE_CLEANED.csv'
# Delimiter: ';', Decimal separator: ','
try:
    df = pd.read_csv(file_path, delimiter=';', encoding='utf-8')
except UnicodeDecodeError:
    # Try a different common encoding if utf-8 fails
    df = pd.read_csv(file_path, delimiter=';', encoding='latin1')

print(f"Original Data Shape: {df.shape}")
print(df.head())

"""Data Cleaning and Preprocessing"""

# Function to clean numeric columns that use a comma as a decimal separator
def clean_numeric_column(series, decimal_separator=','):
    # Replace comma with period for float conversion
    series = series.astype(str).str.replace(decimal_separator, '.', regex=False)
    # Convert to numeric, errors='coerce' turns non-convertible values into NaN
    return pd.to_numeric(series, errors='coerce')

# Clean Avg_Rating
df['Avg_Rating'] = clean_numeric_column(df['Avg_Rating'])

# Clean and convert key columns to integers (int)
df['Ratings_Count'] = clean_numeric_column(df['Ratings_Count']).fillna(0).astype(int)
df['Number of Reviews'] = clean_numeric_column(df['Number of Reviews']).fillna(0).astype(int)
df['Year'] = clean_numeric_column(df['Year']).fillna(0).astype(int)
df['Number of Pages'] = clean_numeric_column(df['Number of Pages']).fillna(0).astype(int)


# Filter out rows where essential data is missing or nonsensical (e.g., Year 0, 0 pages)
df_clean = df.dropna(subset=['Avg_Rating', 'Author', 'Title']).copy()
df_clean = df_clean[df_clean['Year'] > 1000] # Filter out year 0 or clearly invalid years
df_clean = df_clean[df_clean['Number of Pages'] > 0]


print(f"Cleaned Data Shape: {df_clean.shape}\n")
print("First 5 rows of the cleaned dataset:")
print(df_clean.head().to_markdown(numalign="left", stralign="left"))

"""Descriptive Statistics and Correlations

1. Descriptive Statistics
"""

print("--- Descriptive Statistics ---")

# Descriptive statistics for continuous variables
print(df_clean[['Avg_Rating', 'Ratings_Count', 'Number of Reviews', 'Number of Pages']].describe().to_markdown(numalign="left", stralign="left"))

"""2. Correlation Matrix"""

print("\n--- Correlation Matrix (Avg_Rating, Ratings_Count, Pages) ---")
# Calculate correlation between key variables: Rating, Ratings Count, Pages
correlation_matrix = df_clean[['Avg_Rating', 'Ratings_Count', 'Number of Pages']].corr()
print(correlation_matrix.to_markdown(numalign="left", stralign="left"))

"""Analysis of Extreme Values

1. Highest Rated Books
"""

print("\n--- Highest Rated Books (Top 5) ---")
print(df_clean.sort_values(by='Avg_Rating', ascending=False).head(5)[['Title', 'Author', 'Avg_Rating', 'Ratings_Count']].to_markdown(numalign="left", stralign="left"))

"""2. Lowest Rated Books"""

print("\n--- Lowest Rated Books (Top 5, Min 500 Ratings) ---")
# Require a minimum of 500 ratings to ensure the rating is meaningful
low_rated = df_clean[df_clean['Ratings_Count'] >= 500].sort_values(by='Avg_Rating', ascending=True).head(5)
print(low_rated[['Title', 'Author', 'Avg_Rating', 'Ratings_Count']].to_markdown(numalign="left", stralign="left"))

"""Data Visualization"""

plt.figure(figsize=(18, 15))
plt.suptitle('Goodreads Top 10,000 Books Analysis', fontsize=20, y=1.02, fontweight='bold')

"""Plot 1: Distribution of Average Ratings"""

plt.subplot(3, 2, 1)
sns.histplot(df_clean['Avg_Rating'], bins=20, kde=True, edgecolor='black')
plt.title('1. Distribution of Average Book Ratings', fontsize=14)
plt.xlabel('Average Rating (1.0 to 5.0)')
plt.ylabel('Number of Books')
plt.axvline(df_clean['Avg_Rating'].mean(), color='red', linestyle='--', label=f'Mean Rating: {df_clean["Avg_Rating"].mean():.2f}')
plt.legend()

"""Plot 2: Top 10 Authors by Number of Published Books


"""

plt.subplot(3, 2, 2)
top_authors = df_clean['Author'].value_counts().nlargest(10).sort_values(ascending=True)
sns.barplot(x=top_authors.values, y=top_authors.index, orient='h')
plt.title('2. Top 10 Most Frequent Authors in the Dataset', fontsize=14)
plt.xlabel('Number of Books')
plt.ylabel('Author')

"""Plot 3: Relationship between Popularity (Ratings Count) and Quality (Avg Rating)"""

plt.subplot(3, 2, 3)
# Sample data to make the scatter plot readable
df_sample = df_clean.sample(min(5000, len(df_clean)), random_state=42)
sns.scatterplot(x='Ratings_Count', y='Avg_Rating', data=df_sample, alpha=0.6, s=50)
plt.title('3. Average Rating vs. Total Ratings Count (Popularity)', fontsize=14)
plt.xlabel('Ratings Count (Log Scale)')
plt.ylabel('Average Rating')
plt.xscale('log') # Use log scale for readability
plt.tight_layout()

"""Plot 4: Distribution of Publication Years"""

plt.subplot(3, 2, 4)
sns.histplot(df_clean['Year'], bins=30, kde=True, edgecolor='black', color='orange')
plt.title('4. Distribution of Publication Years', fontsize=14)
plt.xlabel('Publication Year')
plt.ylabel('Number of Books')

"""Plot 5: Book Length Distribution (Number of Pages)"""

plt.subplot(3, 2, 5)
# Filter for reasonable page counts (e.g., < 1000 pages) for a better visual
df_pages = df_clean[df_clean['Number of Pages'] < 1000].copy()
sns.violinplot(y=df_pages['Number of Pages'], color='lightgreen')
plt.title('5. Book Length Distribution (Number of Pages)', fontsize=14)
plt.ylabel('Number of Pages')
plt.xlabel('')
plt.xticks([])

""" Plot 6: Top 10 Books by Total Number of Reviews

"""

plt.subplot(3, 2, 6)
top_reviews = df_clean.sort_values('Number of Reviews', ascending=False).head(10)
sns.barplot(x='Number of Reviews', y='Title', data=top_reviews.sort_values('Number of Reviews', ascending=True), orient='h', color='purple')
plt.title('6. Top 10 Most Reviewed Books', fontsize=14)
plt.xlabel('Number of Reviews')
plt.ylabel('Book Title')

""" Adjust layout and display plots"""

plt.tight_layout(rect=[0, 0, 1, 1])
plt.show()

"""ANALYSIS QUESTIONS"""

# ====================
# ANSWERS TO 8 ANALYTICAL QUESTIONS FOR GOODREADS DATASET
# ====================

import pandas as pd
import numpy as np

# Load and clean data
df = pd.read_csv('goodreads_dataset_COMPLETE_CLEANED.csv', delimiter=';', encoding='utf-8')

# Clean numeric columns
def clean_numeric(series, decimal_separator=','):
    series = series.astype(str)
    series = series.str.replace(decimal_separator, '.', regex=False)
    series = series.str.replace(r'[^\d\.\-]', '', regex=True)
    return pd.to_numeric(series, errors='coerce')

# Clean all columns
df['Avg_Rating'] = clean_numeric(df['Avg_Rating'])
df['Ratings_Count'] = clean_numeric(df['Ratings_Count']).fillna(0).astype(int)
df['Year'] = clean_numeric(df['Year']).fillna(0).astype(int)
df['Number of Pages'] = clean_numeric(df['Number of Pages']).fillna(0).astype(int)
df['Number of Reviews'] = clean_numeric(df['Number of Reviews']).fillna(0).astype(int)

# Filter valid data
df_clean = df.dropna(subset=['Avg_Rating', 'Author', 'Title']).copy()
df_clean = df_clean[df_clean['Year'] > 1000]
df_clean = df_clean[df_clean['Number of Pages'] > 0]
df_clean = df_clean[df_clean['Ratings_Count'] > 0]

print(f"📊 Dataset loaded: {len(df_clean):,} books")

"""Question 1"""

# QUESTION 1: Which books have the highest and lowest average ratings?
# ====================

print("\n" + "="*80)
print("1. 📚 BOOKS WITH HIGHEST AND LOWEST AVERAGE RATINGS")
print("="*80)

min_ratings = 1000  # For statistical significance
high_rated = df_clean[df_clean['Ratings_Count'] >= min_ratings]

# Highest rated
top_5_high = high_rated.nlargest(5, 'Avg_Rating')
print("\nTOP 5 HIGHEST RATED BOOKS (≥1,000 ratings):")
for i, (_, row) in enumerate(top_5_high.iterrows(), 1):
    title = str(row['Title'])[:50] + "..." if len(str(row['Title'])) > 50 else str(row['Title'])
    print(f"{i}. {title}")
    print(f"   Author: {row['Author']}")
    print(f"   Rating: {row['Avg_Rating']:.2f} | Ratings: {row['Ratings_Count']:,} | Year: {row['Year']}")

# Lowest rated
top_5_low = high_rated.nsmallest(5, 'Avg_Rating')
print("\nTOP 5 LOWEST RATED BOOKS (≥1,000 ratings):")
for i, (_, row) in enumerate(top_5_low.iterrows(), 1):
    title = str(row['Title'])[:50] + "..." if len(str(row['Title'])) > 50 else str(row['Title'])
    print(f"{i}. {title}")
    print(f"   Author: {row['Author']}")
    print(f"   Rating: {row['Avg_Rating']:.2f} | Ratings: {row['Ratings_Count']:,} | Year: {row['Year']}")

"""Question 2"""

# QUESTION 2: Which authors dominate the "Best Books Ever" list?
# ====================

print("\n" + "="*80)
print("2. 👥 AUTHORS WHO DOMINATE THE 'BEST BOOKS EVER' LIST")
print("="*80)

top_authors = df_clean['Author'].value_counts().head(10)
total_books = len(df_clean)

print("\nTOP 10 MOST FREQUENT AUTHORS:")
for i, (author, count) in enumerate(top_authors.items(), 1):
    percentage = (count / total_books * 100)
    print(f"{i}. {author}: {count} books ({percentage:.1f}%)")

# Concentration analysis
top_5_sum = top_authors.head(5).sum()
top_10_sum = top_authors.sum()
print(f"\n📊 Concentration Analysis:")
print(f"• Top 5 authors: {top_5_sum} books ({top_5_sum/total_books*100:.1f}%)")
print(f"• Top 10 authors: {top_10_sum} books ({top_10_sum/total_books*100:.1f}%)")
print(f"• Average books per author: {total_books/df_clean['Author'].nunique():.1f}")
print(f"• Most prolific author has {top_authors.iloc[0]} books")

"""Question 3"""

# QUESTION 3: Which authors provide the best value?
# ====================

print("\n" + "="*80)
print("3. 💎 AUTHORS PROVIDING BEST VALUE (High Ratings at Reasonable Popularity)")
print("="*80)

author_stats = df_clean.groupby('Author').agg(
    book_count=('Title', 'count'),
    avg_rating=('Avg_Rating', 'mean'),
    avg_popularity=('Ratings_Count', 'mean')
).reset_index()

author_stats = author_stats[author_stats['book_count'] >= 3]

# Value score = rating * log(popularity) - balances quality and reach
author_stats['value_score'] = author_stats['avg_rating'] * np.log1p(author_stats['avg_popularity'])
best_value = author_stats.nlargest(5, 'value_score')

print("\nTOP 5 BEST VALUE AUTHORS:")
for i, (_, row) in enumerate(best_value.iterrows(), 1):
    print(f"{i}. {row['Author']}")
    print(f"   Avg Rating: {row['avg_rating']:.2f}/5.00")
    print(f"   Avg Popularity: {row['avg_popularity']:,.0f} ratings per book")
    print(f"   Books in list: {row['book_count']}")
    print(f"   Value Score: {row['value_score']:.3f}")

# Also show worst value (high popularity, low rating)
worst_value = author_stats[author_stats['avg_popularity'] > 50000].nsmallest(3, 'value_score')
if len(worst_value) > 0:
    print("\n📉 AUTHORS WITH POOR VALUE (High Popularity, Low Rating):")
    for i, (_, row) in enumerate(worst_value.iterrows(), 1):
        print(f"{i}. {row['Author']} - Rating: {row['avg_rating']:.2f}, Popularity: {row['avg_popularity']:,.0f}")

"""Question 4"""

# QUESTION 4: Do longer books (more pages) receive higher ratings?
# ====================

print("\n" + "="*80)
print("4. 📖 DO LONGER BOOKS RECEIVE HIGHER RATINGS?")
print("="*80)

corr_pages_rating = df_clean['Number of Pages'].corr(df_clean['Avg_Rating'])
print(f"\nCorrelation between book length and rating: {corr_pages_rating:.3f}")

# Create length categories
df_clean['Length_Category'] = pd.cut(df_clean['Number of Pages'],
                                     bins=[0, 200, 300, 400, 500, 1000, 10000],
                                     labels=['<200', '200-300', '300-400', '400-500', '500-1000', '>1000'])

length_stats = df_clean.groupby('Length_Category').agg({
    'Avg_Rating': ['mean', 'count'],
    'Number of Pages': 'mean'
}).round(2)

print("\n📏 AVERAGE RATING BY BOOK LENGTH:")
for category in length_stats.index:
    if category in df_clean['Length_Category'].unique():
        mean_rating = length_stats.loc[category, ('Avg_Rating', 'mean')]
        book_count = length_stats.loc[category, ('Avg_Rating', 'count')]
        avg_pages = length_stats.loc[category, ('Number of Pages', 'mean')]
        print(f"• {category} pages: {mean_rating:.2f} (avg {avg_pages:.0f} pages, {book_count} books)")

# Find optimal length
optimal_length = length_stats[('Avg_Rating', 'mean')].idxmax()
optimal_rating = length_stats.loc[optimal_length, ('Avg_Rating', 'mean')]
print(f"\n🎯 Optimal length: {optimal_length} pages with average rating of {optimal_rating:.2f}")

"""Question 5"""

# QUESTION 5: Relationship between popularity and average rating
# ====================

print("\n" + "="*80)
print("5. 📈 RELATIONSHIP BETWEEN POPULARITY AND AVERAGE RATING")
print("="*80)

corr_popularity_rating = df_clean['Ratings_Count'].corr(df_clean['Avg_Rating'])
print(f"\nCorrelation: {corr_popularity_rating:.3f}")

# Create popularity quartiles
df_clean['Popularity_Quartile'] = pd.qcut(df_clean['Ratings_Count'], 4,
                                         labels=['Q1 (Least Popular)', 'Q2', 'Q3', 'Q4 (Most Popular)'])

quartile_stats = df_clean.groupby('Popularity_Quartile').agg({
    'Avg_Rating': 'mean',
    'Ratings_Count': ['min', 'max', 'median'],
    'Title': 'count'
}).round(2)

print("\n📊 RATING BY POPULARITY QUARTILE:")
for quartile in quartile_stats.index:
    avg_rating = quartile_stats.loc[quartile, ('Avg_Rating', 'mean')]
    min_ratings = quartile_stats.loc[quartile, ('Ratings_Count', 'min')]
    max_ratings = quartile_stats.loc[quartile, ('Ratings_Count', 'max')]
    median_ratings = quartile_stats.loc[quartile, ('Ratings_Count', 'median')]
    count = quartile_stats.loc[quartile, ('Title', 'count')]

    print(f"• {quartile}:")
    print(f"  Avg Rating: {avg_rating:.2f}")
    print(f"  Ratings Range: {min_ratings:,.0f} - {max_ratings:,.0f}")
    print(f"  Median Ratings: {median_ratings:,.0f}")
    print(f"  Books: {count}")

# Analyze extremes
print(f"\n🔍 EXTREME CASES:")
most_popular = df_clean.nlargest(1, 'Ratings_Count').iloc[0]
highest_rated_popular = df_clean[df_clean['Ratings_Count'] > 100000].nlargest(1, 'Avg_Rating').iloc[0]

print(f"• Most popular book: '{most_popular['Title'][:40]}...'")
print(f"  Ratings: {most_popular['Ratings_Count']:,}, Score: {most_popular['Avg_Rating']:.2f}")

print(f"• Highest rated among popular (>100K ratings): '{highest_rated_popular['Title'][:40]}...'")
print(f"  Ratings: {highest_rated_popular['Ratings_Count']:,}, Score: {highest_rated_popular['Avg_Rating']:.2f}")

"""Question 6"""

# QUESTION 6: Are some popular books overrated?
# ====================

print("\n" + "="*80)
print("6. ⚖️ ARE SOME POPULAR BOOKS OVERRATED?")
print("="*80)

# Calculate expected rating based on popularity trend
baseline = df_clean['Avg_Rating'].median()
df_clean['Log_Ratings'] = np.log1p(df_clean['Ratings_Count'])
df_clean['Expected_Rating'] = baseline + 0.05 * (df_clean['Log_Ratings'] - df_clean['Log_Ratings'].median())
df_clean['Rating_Gap'] = df_clean['Avg_Rating'] - df_clean['Expected_Rating']

# Find overrated books (high popularity, low rating relative to expectation)
popular_books = df_clean[df_clean['Ratings_Count'] > 50000]
if len(popular_books) > 0:
    overrated = popular_books.nsmallest(5, 'Rating_Gap')

    print("\n📉 TOP 5 POTENTIALLY OVERRATED BOOKS:")
    print("(High popularity, lower than expected rating)")
    for i, (_, row) in enumerate(overrated.iterrows(), 1):
        title = str(row['Title'])[:40] + "..." if len(str(row['Title'])) > 40 else str(row['Title'])
        print(f"{i}. {title}")
        print(f"   Author: {row['Author']}")
        print(f"   Actual: {row['Avg_Rating']:.2f}, Expected: {row['Expected_Rating']:.2f}")
        print(f"   Gap: {row['Rating_Gap']:+.2f} (negative = overrated)")
        print(f"   Popularity: {row['Ratings_Count']:,} ratings")

    # Also show underrated (low popularity, high rating)
    underrated = popular_books.nlargest(3, 'Rating_Gap')
    print("\n🌟 TOP 3 POTENTIALLY UNDERRATED BOOKS:")
    print("(High rating relative to popularity)")
    for i, (_, row) in enumerate(underrated.iterrows(), 1):
        title = str(row['Title'])[:40] + "..." if len(str(row['Title'])) > 40 else str(row['Title'])
        print(f"{i}. {title} - Rating: {row['Avg_Rating']:.2f}, Gap: {row['Rating_Gap']:+.2f}")
else:
    print("\nNo books with > 50,000 ratings found for this analysis.")

"""Question 7"""

# QUESTION 7: How have book ratings changed over decades?
# ====================

print("\n" + "="*80)
print("7. 📅 BOOK RATING TRENDS OVER DECADES")
print("="*80)

df_clean['Decade'] = (df_clean['Year'] // 10) * 10
decade_data = df_clean[(df_clean['Decade'] >= 1900) & (df_clean['Decade'] <= 2020)]

if len(decade_data) > 0:
    decade_stats = decade_data.groupby('Decade').agg({
        'Avg_Rating': ['mean', 'count', 'std'],
        'Ratings_Count': 'mean',
        'Number of Pages': 'mean'
    }).round(3)

    print("\n📈 DECADE-BY-DECADE ANALYSIS (1900-2020):")
    print(f"{'Decade':<10} {'Avg Rating':<12} {'Books':<8} {'Avg Pages':<12} {'Avg Ratings':<12}")
    print("-" * 60)

    for decade in sorted(decade_stats.index):
        mean_rating = decade_stats.loc[decade, ('Avg_Rating', 'mean')]
        book_count = int(decade_stats.loc[decade, ('Avg_Rating', 'count')])
        avg_pages = decade_stats.loc[decade, ('Number of Pages', 'mean')]
        avg_ratings = decade_stats.loc[decade, ('Ratings_Count', 'mean')]

        if book_count >= 5:  # Show only decades with enough data
            print(f"{decade:<10} {mean_rating:<12.2f} {book_count:<8} {avg_pages:<12.0f} {avg_ratings:<12,.0f}")

    # Trend analysis
    recent_decades = [d for d in [1980, 1990, 2000, 2010] if d in decade_stats.index]
    if len(recent_decades) >= 2:
        print("\n📊 RECENT TRENDS:")
        for i in range(len(recent_decades)-1):
            decade1 = recent_decades[i]
            decade2 = recent_decades[i+1]
            rating1 = decade_stats.loc[decade1, ('Avg_Rating', 'mean')]
            rating2 = decade_stats.loc[decade2, ('Avg_Rating', 'mean')]
            change = ((rating2 - rating1) / rating1 * 100)

            trend = "↑" if change > 0 else "↓"
            print(f"{decade1}s → {decade2}s: {rating1:.2f} → {rating2:.2f} ({change:+.1f}%) {trend}")
else:
    print("Insufficient data for decade analysis.")

"""Question 8"""

# QUESTION 8: Do higher-rated books generate more written reviews?
# ====================

print("\n" + "="*80)
print("8. 💬 DO HIGHER-RATED BOOKS GENERATE MORE WRITTEN REVIEWS?")
print("="*80)

# Calculate review ratio safely
df_clean['Review_Ratio'] = df_clean['Number of Reviews'] / df_clean['Ratings_Count'].replace(0, np.nan)
valid_reviews = df_clean[df_clean['Review_Ratio'].notna() & (df_clean['Review_Ratio'] <= 1)]

if len(valid_reviews) > 0:
    corr_review_rating = valid_reviews['Review_Ratio'].corr(valid_reviews['Avg_Rating'])
    print(f"\nCorrelation between rating and review ratio: {corr_review_rating:.3f}")

    # Create rating tiers
    valid_reviews['Rating_Tier'] = pd.cut(valid_reviews['Avg_Rating'],
                                        bins=[0, 3.0, 3.5, 4.0, 4.5, 5.0],
                                        labels=['<3.0', '3.0-3.5', '3.5-4.0', '4.0-4.5', '4.5+'])

    tier_stats = valid_reviews.groupby('Rating_Tier').agg({
        'Review_Ratio': ['mean', 'count'],
        'Avg_Rating': 'mean',
        'Ratings_Count': 'mean'
    }).round(4)

    print("\n📝 REVIEW ENGAGEMENT BY RATING TIER:")
    for tier in tier_stats.index:
        if tier in valid_reviews['Rating_Tier'].unique():
            review_ratio = tier_stats.loc[tier, ('Review_Ratio', 'mean')]
            book_count = int(tier_stats.loc[tier, ('Review_Ratio', 'count')])
            avg_rating = tier_stats.loc[tier, ('Avg_Rating', 'mean')]
            avg_ratings = tier_stats.loc[tier, ('Ratings_Count', 'mean')]

            print(f"• {tier} stars (avg: {avg_rating:.2f}):")
            print(f"  Review Ratio: {review_ratio:.4f} ({review_ratio*100:.1f}% of ratings are reviews)")
            print(f"  Avg Ratings per Book: {avg_ratings:,.0f}")
            print(f"  Books in tier: {book_count}")

    # Find books with exceptional review engagement
    high_engagement = valid_reviews.nlargest(3, 'Review_Ratio')
    print("\n🏆 BOOKS WITH EXCEPTIONAL REVIEW ENGAGEMENT:")
    for i, (_, row) in enumerate(high_engagement.iterrows(), 1):
        title = str(row['Title'])[:40] + "..." if len(str(row['Title'])) > 40 else str(row['Title'])
        review_ratio = row['Review_Ratio']
        print(f"{i}. {title}")
        print(f"   Rating: {row['Avg_Rating']:.2f}, Review Ratio: {review_ratio:.4f} ({review_ratio*100:.1f}%)")
        print(f"   Reviews: {row['Number of Reviews']:,}, Ratings: {row['Ratings_Count']:,}")
else:
    print("Insufficient review data for analysis.")

"""Final Summary"""

# FINAL SUMMARY
# ====================

print("\n" + "="*80)
print("📋 EXECUTIVE SUMMARY")
print("="*80)

print(f"""
KEY FINDINGS:

1. RATING RANGE: Books range from {top_5_low['Avg_Rating'].min():.2f} to {top_5_high['Avg_Rating'].max():.2f}
   with most concentrated around {df_clean['Avg_Rating'].median():.2f}

2. AUTHOR DOMINATION: Strong concentration - top 10 authors account for
   {top_10_sum/total_books*100:.1f}% of all books

3. BEST VALUE AUTHORS: {best_value.iloc[0]['Author']} offers best value with
   {best_value.iloc[0]['avg_rating']:.2f} rating at {best_value.iloc[0]['avg_popularity']:,.0f} avg popularity

4. LENGTH VS RATING: Minimal correlation ({corr_pages_rating:.3f})
   Optimal length: {optimal_length} pages ({optimal_rating:.2f} avg rating)

5. POPULARITY PARADOX: Weak correlation ({corr_popularity_rating:.3f}) suggests
   popularity doesn't guarantee higher ratings

6. OVERRATED BOOKS: {len(popular_books[popular_books['Rating_Gap'] < -0.1]) if 'popular_books' in locals() else 0}
   popular books rated lower than expected

7. TEMPORAL TREND: {'Improving' if 'change' in locals() and change > 0 else 'Stable/Declining'}
   ratings in recent decades

8. REVIEW ENGAGEMENT: {'Positive' if 'corr_review_rating' in locals() and corr_review_rating > 0.1 else 'Weak'}
   correlation ({corr_review_rating if 'corr_review_rating' in locals() else 0:.3f}) between rating and reviews

DATASET: {len(df_clean):,} books | Avg Rating: {df_clean['Avg_Rating'].mean():.2f} |
Avg Pages: {df_clean['Number of Pages'].mean():.0f} | Years: {df_clean['Year'].min()}-{df_clean['Year'].max()}
""")
